name: release

on:
  push:
    tags: [ v* ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        machine: [ windows-2022, ubuntu-20.04, macos-11 ]
    runs-on: ${{ matrix.machine }}
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: | 
            6.0.x
            7.0.x
      - run: ./build.cmd
      - name: Upload binaries
        uses: actions/upload-artifact@v3.1.2
        if: always()
        with:
          name: bin-${{ matrix.machine }}
          path: bin/tracer-home

  container-build:
    name: Container Build 
    strategy:
      fail-fast: false
      matrix:
        base-image: [ alpine ]
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3.5.2
    - name: Build Docker image
      run: |
        docker build \
          --tag otel-dotnet-autoinstrumentation/${{ matrix.base-image }} \
          --file "./docker/${{ matrix.base-image }}.dockerfile" \
          ./build
    - name: Build in Docker container
      run: |
        docker run --rm \
          --mount type=bind,source="${GITHUB_WORKSPACE}",target=/project \
          otel-dotnet-autoinstrumentation/${{ matrix.base-image }} \
          ./build.sh
    - name: Upload ${{ matrix.base-image }} binaries
      uses: actions/upload-artifact@v3.1.2
      if: always()
      with:
        name: bin-${{ matrix.base-image }}
        path: bin/tracer-home

  pack:
    needs: build

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: nuget/setup-nuget@v1.1.1

      - name: Download Windows Artifacts from build job
        uses: actions/download-artifact@v3.0.2
        with:
          name: bin-windows-2022
          path: nuget/bin-windows

      - name: Download Ubuntu Artifacts from build job
        uses: actions/download-artifact@v3.0.2
        with:
          name: bin-ubuntu-20.04
          path: nuget/bin-linux-glibc

      - name: Download Alpine Artifacts from build job
        uses: actions/download-artifact@v3.0.2
        with:
          name: bin-alpine
          path: nuget/bin-linux-musl

      - name: Download Mac-OS Artifacts from build job
        uses: actions/download-artifact@v3.0.2
        with:
          name: bin-macos-11
          path: nuget/bin-macos

      - name: Build NuGet package
        run: nuget pack OpenTelemetry.AutoInstrumentation.nuspec -Properties NoWarn=NU5100,NU5123,NU5128
        working-directory: nuget

      - name: Upload Nuget
        uses: actions/upload-artifact@v3.1.2
        with:
          name: OpenTelemetry.AutoInstrumentation.Nuget
          path: nuget/*.nupkg
